CREATE TABLE tfg.cities (
    ibge_code INT PRIMARY KEY,
    region VARCHAR(256) NOT NULL,
    city_name VARCHAR(256) NOT NULL,
    lat_city FLOAT,
    long_city FLOAT,
    capital INT,
    state_id INT NOT NULL,
    state_name VARCHAR(256),
    state_code CHAR(2),
    lat_state FLOAT,
    long_state FLOAT
);

CREATE TABLE tfg.enem (
    id VARCHAR(12) PRIMARY KEY,
    enem_year INT,
    age INT,
    sex ENUM('M', 'F'),
    marital_status INT,
    color_race INT,
    id_city_school INT,
    id_city_test INT,
    high_school_status INT,
    year_completion_high_school INT,
    school_type INT,
    presence_day_1 INT,
    presence_day_2 INT,
    nature_sciences_score FLOAT,
    human_sciences_score FLOAT,
    languages_codes_score FLOAT,
    mathematics_score FLOAT,
    spelling_score FLOAT,
    understanding_score FLOAT,
    structuring_score FLOAT,
    argumentation_score FLOAT,
    proposal_score FLOAT,
    redaction_score FLOAT,
    father_schooling CHAR(1),
    mother_schooling CHAR(1),
    father_profession_group CHAR(1),
    mother_profession_group CHAR(1),
    family_income VARCHAR(128),
    members_qty INT,
    bedrooms_qty CHAR(1),
    cars_qty CHAR(1),
    television_qty CHAR(1),
    phones_qty CHAR(1),
    computers_qty CHAR(1),
    internet_access CHAR(1),
    FOREIGN KEY (id_city_school) REFERENCES tfg.cities(ibge_code),
    FOREIGN KEY (id_city_test) REFERENCES tfg.cities(ibge_code)
);

CREATE TABLE tfg.censo_educacao_basica (
    id_escola INT PRIMARY KEY,
    id_municipio INT NOT NULL,
    nome_escola VARCHAR(256),
    situacao INT,
    localizacao INT,
    ano_censo INT,
    dependencia INT,
    agua_potavel INT,
    energia INT,
    esgoto INT,
    coleta_lixo INT,
    laboratorio_ciencias INT,
    laboratorio_informatica INT,
    piscina INT,
    quadra_esportes INT,
    qtd_salas_utilizadas INT,
    qtd_desktop_aluno INT,
    qtd_notebook_aluno INT,
    qtd_tablet_aluno INT,
    internet_alunos INT,
    internet_aprendizagem INT,
    qtd_administrativos INT,
    qtd_servicos_gerais INT,
    qtd_bibliotecario INT,
    qtd_psicologo INT,
    qtd_alimentacao INT,
    qtd_pedagogia INT,
    qtd_seguranca INT,
    fornece_alimentacao INT,
    material_multimidia INT,
    material_cientifico INT,
    material_musical INT,
    material_jogos INT,
    material_artistico INT,
    material_desportivo INT,
    material_etnico INT,
    atividade_complementar INT,
    espaco_atividade INT,
    espaco_equipamento INT,
    redes_sociais INT,
    qtd_alunos_basico INT,
    qtd_alunos_infantil INT,
    qtd_alunos_fundamental INT,
    qtd_alunos_medio INT,
    qtd_alunos_profissional INT,
    qtd_alunos_profissional_tec INT,
    qtd_alunos_nd INT,
    qtd_alunos_branca INT,
    qtd_alunos_preta INT,
    qtd_alunos_parda INT,
    qtd_alunos_amarela INT,
    qtd_alunos_indigena INT,
    qtd_alunos_diurno INT,
    qtd_alunos_noturno INT,
    qtd_alunos_ead INT,
    qtd_docente_basico INT,
    qtd_docente_infantil INT,
    qtd_docente_fundamental INT,
    qtd_docente_medio INT,
    qtd_docente_profissional INT,
    qtd_docente_profissional_tec INT,
    qtd_turma_basico INT,
    qtd_turma_infantil INT,
    qtd_turma_fundamental INT,
    qtd_turma_medio INT,
    qtd_turma_profissional INT,
    qtd_turma_profissional_tec INT,
    FOREIGN KEY (id_municipio) REFERENCES tfg.cities(ibge_code)
);