CREATE TABLE tfg.municipios (
    codigo_ibge INT PRIMARY KEY,
    regiao VARCHAR(256) NOT NULL,
    municipio VARCHAR(256) NOT NULL,
    lat_mun FLOAT,
    long_mun FLOAT,
    capital INT,
    codigo_uf INT NOT NULL,
    uf VARCHAR(256),
    sigla_uf CHAR(2),
    lat_uf FLOAT,
    long_uf FLOAT
);

CREATE TABLE tfg.censo_educacao_basica (
    id_escola INT PRIMARY KEY,
    id_municipio INT NOT NULL,
    nome_escola VARCHAR(256),
    situacao INT,
    localizacao INT,
    ano_censo INT,
    dependencia INT,
    agua_potavel INT,
    energia INT,
    esgoto INT,
    coleta_lixo INT,
    laboratorio_ciencias INT,
    laboratorio_informatica INT,
    piscina INT,
    quadra_esportes INT,
    qtd_salas_utilizadas INT,
    qtd_desktop_aluno INT,
    qtd_notebook_aluno INT,
    qtd_tablet_aluno INT,
    internet_alunos INT,
    internet_aprendizagem INT,
    qtd_administrativos INT,
    qtd_servicos_gerais INT,
    qtd_bibliotecario INT,
    qtd_psicologo INT,
    qtd_alimentacao INT,
    qtd_pedagogia INT,
    qtd_seguranca INT,
    fornece_alimentacao INT,
    material_multimidia INT,
    material_cientifico INT,
    material_musical INT,
    material_jogos INT,
    material_artistico INT,
    material_desportivo INT,
    material_etnico INT,
    atividade_complementar INT,
    espaco_atividade INT,
    espaco_equipamento INT,
    redes_sociais INT,
    qtd_alunos_basico INT,
    qtd_alunos_infantil INT,
    qtd_alunos_fundamental INT,
    qtd_alunos_medio INT,
    qtd_alunos_profissional INT,
    qtd_alunos_profissional_tec INT,
    qtd_alunos_nd INT,
    qtd_alunos_branca INT,
    qtd_alunos_preta INT,
    qtd_alunos_parda INT,
    qtd_alunos_amarela INT,
    qtd_alunos_indigena INT,
    qtd_alunos_diurno INT,
    qtd_alunos_noturno INT,
    qtd_alunos_ead INT,
    qtd_docente_basico INT,
    qtd_docente_infantil INT,
    qtd_docente_fundamental INT,
    qtd_docente_medio INT,
    qtd_docente_profissional INT,
    qtd_docente_profissional_tec INT,
    qtd_turma_basico INT,
    qtd_turma_infantil INT,
    qtd_turma_fundamental INT,
    qtd_turma_medio INT,
    qtd_turma_profissional INT,
    qtd_turma_profissional_tec INT,
    FOREIGN KEY (id_municipio) REFERENCES tfg.municipios(codigo_ibge)
);

CREATE TABLE tfg.enem (
    id_inscricao VARCHAR(12) PRIMARY KEY,
    enem_ano INT,
    idade INT,
    sexo ENUM('M', 'F'),
    estado_civil INT,
    cor_raca INT,
    id_municipio_escola INT,
    id_municipio_prova INT,
    status_ensino_medio INT,
    ano_conclusao_ensino_medio INT,
    tipo_escola INT,
    presenca_dia_1 INT,
    presenca_dia_2 INT,
    nota_ciencias_natureza FLOAT,
    nota_ciencias_humanas FLOAT,
    nota_linguagens_codigos FLOAT,
    nota_matematica FLOAT,
    nota_ortografia FLOAT,
    nota_entendimento FLOAT,
    nota_estruturacao FLOAT,
    nota_argumentacao FLOAT,
    nota_proposta FLOAT,
    nota_redacao FLOAT,
    escolaridade_pai CHAR(1),
    escolaridade_mae CHAR(1),
    grupo_ocupacao_pai CHAR(1),
    grupo_ocupacao_mae CHAR(1),
    renda_familiar VARCHAR(128),
    qtd_moradores INT,
    qtd_quartos CHAR(1),
    qtd_carros CHAR(1),
    qtd_televisao CHAR(1),
    qtd_celular CHAR(1),
    qtd_computador CHAR(1),
    possui_internet CHAR(1),
    FOREIGN KEY (id_municipio_escola) REFERENCES tfg.municipios(codigo_ibge),
    FOREIGN KEY (id_municipio_prova) REFERENCES tfg.municipios(codigo_ibge)
);
