CREATE TABLE tfg.cities (
  ibge_code INT PRIMARY KEY,
  region VARCHAR(256) NOT NULL,
  city_name VARCHAR(256) NOT NULL,
  lat_city FLOAT,
  long_city FLOAT,
  capital INT,
  state_id INT NOT NULL,
  state_name VARCHAR(256),
  state_code CHAR(2),
  lat_state FLOAT,
  long_state FLOAT
);

CREATE TABLE tfg.enem (
  id VARCHAR(64) PRIMARY KEY,
  enem_year INT DEFAULT NULL,
  age INT DEFAULT NULL,
  sex CHAR,
  marital_status INT DEFAULT NULL,
  color_race INT DEFAULT NULL,
  high_school_status INT DEFAULT NULL,
  year_completion_high_school INT DEFAULT NULL,
  school_type INT DEFAULT NULL,
  id_city_school VARCHAR(64),
  city_school VARCHAR(64),
  state_school VARCHAR(64),
  id_city_test VARCHAR(64),
  city_test VARCHAR(64),
  state_test VARCHAR(64),
  presence_day_1 INT DEFAULT NULL,
  presence_day_2 INT DEFAULT NULL,
  nature_science_score FLOAT,
  human_sciences_score FLOAT,
  languages_codes_score FLOAT,
  mathematics_score FLOAT,
  ortography_score FLOAT,
  understanding_score FLOAT,
  structuring_score FLOAT,
  argumentation_score FLOAT,
  proposal_score FLOAT,
  redaction_score FLOAT,
  father_schooling CHAR,
  mother_schooling CHAR,
  father_profession_group CHAR,
  mother_profession_group CHAR,
  family_members INT DEFAULT NULL,
  family_income CHAR,
  bedrooms_qty CHAR,
  cars_qty CHAR,
  television_qty CHAR,
  phones_qty CHAR,
  computer_qty CHAR,
  internet_access CHAR
)
